openapi: 3.0.0
info:
  version: 1.0.0
  title: CovidWatch API
  description: An API for submitting reports upon testing positive for covid19 fetching reports to check for contact events

paths:
  /reports:
    # GET request, to be an open endpoint for fteching reports
    get:
      description: Returns a list of reports posted since the timestamp specified
      # /reports?timestamp=<timestamp>
      parameters:
        - in: query
          name: timestamp
          schema:
            type: integer
          description: Fetch reports uploaded since timestamp
      responses:
        '200':
          description: Successfully fetched reports
          content:
            text/plain:
              schema:
                # sends concatenated reports to be consumed and parsed
                # by a library that implements TCN protocol.
                # documentation for the protocol can be found at
                # https://github.com/TCNCoalition/TCN/blob/main/README.md
                type: string
                format: byte
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    post:
      description: Upload a report after positive test
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              # sends concatenated values in report as specified by
              # TCN protocol
              # documentation for the protocol can be found at
              # https://github.com/TCNCoalition/TCN/blob/main/README.md
              type: string
              format: byte
      responses:
        '200':
          description: Successfully uploaded a report
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
